FROM node:9-alpine
MAINTAINER li xu cheng "lixucheng@aliyun.com"

RUN apk update && apk add ffmpeg && rm -rf /var/cache/apk/*

RUN mkdir -p /usr/app/src
WORKDIR /usr/app/src
VOLUME /usr/app/src
EXPOSE 8080 9856
