version: "2"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.ppc64le
    image: cognitive-solution-dashboard
    container_name: cs-dashboard
    environment:
      - AI_VISION_API=http://9.186.106.213:9080/powerai-vision/api
      - Video_Stream_API=http://9.186.106.213:8083/video_demo/stream
      - MongoDB_URI=mongodb://dashboard_mongo:27017/cognitive_solution
    links:
      - mongodb:dashboard_mongo
    ports:
      - "8084:8080"
    volumes:
      - /data/upload:/usr/app/src/upload
    restart: always
  mongodb:
    image: ppc64le/mongodb:2.6.10
    volumes:
      - /data/db:/data/db
    restart: always
