version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: cognitive-solution-dashboard
    container_name: cs-dashboard
    environment:
      - AI_VISION_API=${AI_VISION_API:-http://9.186.106.206:9080/powerai-vision/api}
      - Video_Stream_API=${Video_Stream_API:-http://9.186.106.206:8083/demo_video/stream}
      - MongoDB_URI=${MongoDB_URI:-mongodb://dashboard_mongo:27017/cognitive_solution}
    volumes:
      - ./:/usr/app/src
    links:
      - mongodb:dashboard_mongo
    ports:
      - "8080:8080"
      - "9856:9856"
    command: npm run dev
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
